name: Build and Push Docker Image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: git clone https://github.com/goquati/frappe-docker-image.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute Apps config
        id: compute-apps-config
        run: |
          JSON='[{"url":"https://github.com/frappe/lms","branch":"v2.21.0"}]'
          echo "APPS=$(echo $JSON | base64 -w 0)" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frappe-docker-image
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_TAG_VERSION=${{ github.ref_name }}
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-15
            PYTHON_VERSION=3.11.9
            NODE_VERSION=18.20.2
            APPS_JSON_BASE64=${{ steps.compute-apps-config.outputs.APPS }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frappe-lms:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frappe-lms:${{ github.ref_name }}
